<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521133316 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE project_members (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) DEFAULT \'member\' NOT NULL, assigned_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, project_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D3BEDE9A166D1F9C ON project_members (project_id)');
        $this->addSql('CREATE INDEX IDX_D3BEDE9AA76ED395 ON project_members (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uk_project_user ON project_members (project_id, user_id)');
        $this->addSql('CREATE TABLE project_statuses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, color VARCHAR(7) DEFAULT \'#000000\' NOT NULL, sort_order INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, planned_start_date DATE DEFAULT NULL, planned_end_date DATE DEFAULT NULL, actual_end_date DATE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status_id INT DEFAULT NULL, created_by INT NOT NULL, updated_by INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5C93B3A46BF700BD ON projects (status_id)');
        $this->addSql('CREATE INDEX IDX_5C93B3A4DE12AB56 ON projects (created_by)');
        $this->addSql('CREATE INDEX IDX_5C93B3A416FE72E1 ON projects (updated_by)');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9A166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE project_members ADD CONSTRAINT FK_D3BEDE9AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A46BF700BD FOREIGN KEY (status_id) REFERENCES project_statuses (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A4DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects ADD CONSTRAINT FK_5C93B3A416FE72E1 FOREIGN KEY (updated_by) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9A166D1F9C');
        $this->addSql('ALTER TABLE project_members DROP CONSTRAINT FK_D3BEDE9AA76ED395');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A46BF700BD');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A4DE12AB56');
        $this->addSql('ALTER TABLE projects DROP CONSTRAINT FK_5C93B3A416FE72E1');
        $this->addSql('DROP TABLE project_members');
        $this->addSql('DROP TABLE project_statuses');
        $this->addSql('DROP TABLE projects');
    }
}
