<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520113000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE department (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, organization_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CD1DE18A32C8A3DE ON department (organization_id)');
        $this->addSql('CREATE TABLE department_employee_roles (department_id INT NOT NULL, role_id INT NOT NULL, PRIMARY KEY (department_id, role_id))');
        $this->addSql('CREATE INDEX IDX_4436D7BAE80F5DF ON department_employee_roles (department_id)');
        $this->addSql('CREATE INDEX IDX_4436D7BD60322AC ON department_employee_roles (role_id)');
        $this->addSql('ALTER TABLE department ADD CONSTRAINT FK_CD1DE18A32C8A3DE FOREIGN KEY (organization_id) REFERENCES organization (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE department_employee_roles ADD CONSTRAINT FK_4436D7BAE80F5DF FOREIGN KEY (department_id) REFERENCES department (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE department_employee_roles ADD CONSTRAINT FK_4436D7BD60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE department DROP CONSTRAINT FK_CD1DE18A32C8A3DE');
        $this->addSql('ALTER TABLE department_employee_roles DROP CONSTRAINT FK_4436D7BAE80F5DF');
        $this->addSql('ALTER TABLE department_employee_roles DROP CONSTRAINT FK_4436D7BD60322AC');
        $this->addSql('DROP TABLE department');
        $this->addSql('DROP TABLE department_employee_roles');
    }
}
